Repository Operations-Research-lib/ORLib, pull requests merged in 2023-12, with the labels that each got.

#6 Create sonarcloud.yml
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: documentation, CI/CD

#7 updating develop
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: CI/CD

#8 Update sonarcloud.yml to analize on push to every branch
  .github/workflows/sonarcloud.yml
Labels: CI/CD

#9 updates develop with ci pipeline
  .github/workflows/sonarcloud.yml
Labels: CI/CD

#10 merge Item/ORlib-1 to develop branch
  .gitignore
  src/queueing_theory.py
  src/simulation_and_rand.py
  src/test_queueing_theory.py
Labels: testing

#11 Add Jorge Sagot to contributors list
  README.md
Labels: documentation

#12 update readme and add mm1 unit test
  .gitignore
  README.md
  src/queueing_theory.py
  src/simulation_and_rand.py
  src/test_queueing_theory.py
Labels: documentation, testing
